# Generated by Django 3.2.9 on 2021-11-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(blank=True, max_length=15, null=True)),
                ('Lname', models.CharField(max_length=15)),
                ('Address', models.CharField(blank=True, max_length=15, null=True)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
    ]
