# Generated by Django 3.2.9 on 2021-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silling', '0002_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='Hasbands',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='albums',
            name='Write',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
