# Generated by Django 3.2.9 on 2021-12-30 10:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silling', '0005_auto_20211230_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.RemoveField(
            model_name='type',
            name='Color',
        ),
        migrations.AddField(
            model_name='type',
            name='Type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
