# Generated by Django 3.2.9 on 2021-12-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silling', '0006_auto_20211230_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='file',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
