# Generated by Django 3.2.9 on 2022-01-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silling', '0007_write_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='file',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
