# Generated by Django 3.2.9 on 2022-01-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silling', '0008_albums_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='state',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
