# Generated by Django 3.2.9 on 2022-01-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silling', '0009_albums_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albums',
            name='fold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albums',
            name='mag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albums',
            name='many',
            field=models.BooleanField(default=False),
        ),
    ]
