# Generated by Django 3.2.9 on 2022-01-10 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('silling', '0010_auto_20220105_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albums',
            name='photoshop',
            field=models.BooleanField(default=False),
        ),
    ]
